sudo: required
language: python
python:
  - "3.6"

before_install:
  - sudo apt-get install -y pandoc
addons:
  apt:
    update: true

script:
  - pip install requests
  - wget -q https://github.com/yshalsager/telegram.py/raw/master/telegram.py
  - chmod +x sync.sh
  - ./sync.sh
