sudo: required
language: python
python:
  - "3.6"

before_install:
 - sudo apt-get install -y pandoc
 - |
   if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|^(LICENSE)'
   then
     echo "Not running CI since only docs were changed."
     exit
   fi
addons:
  apt:
    update: true

script:
  - wget -q https://github.com/yshalsager/telegram.py/raw/master/telegram.py
  - chmod +x sync.sh
  - ./sync.sh
